#ENC[AES256_GCM,data:QEspdeTo9wi5mRCA51lP6/0+lfUNnurwopNxaajXxR6RrHO1AByT54zuK3dFYwt+9CAdOgCsL6HU0s/uPSoy6W/y3W3g84NMfeU=,iv:zbub7lLIIN1P4oyhVuO+Ox8KUq2XBnMmbiqOF56Q6JE=,tag:3E5AUx0MmHnwkqiG4JIq2g==,type:comment]
#ENC[AES256_GCM,data:W7APwzEe+pKLzfGUWOf7cqwQQRqM15qqmUxgz5r4Kul7pxyMZWK4klNCxL5JCvalWfhop+0Bn/TPDurDM/DJt4gz6Idw,iv:5ltiLmVHi19wJPLnhuNnr7szAqLJZolVJRsVaheRquo=,tag:QBiwwfmha7/Y+txMQp2pZw==,type:comment]
#ENC[AES256_GCM,data:S+SESTiRGxu6h4KHg7QXR8D4pI9QiMMYFclKhkQCGD6VY2CABtEa3Q==,iv:wF75V6eQ0iKXOJ8iFbtIoUaIQHI87UNxifTD3OGTJps=,tag:zi+eenOc51sLWh/OHcGEyA==,type:comment]
apiVersion: ENC[AES256_GCM,data:ONg=,iv:ayahM4Bc2s+xIiUO4UZOIN7oYwjc4HRJsr8svelLg2I=,tag:hK9DLape3GwdynrYxaXaiA==,type:str]
kind: ENC[AES256_GCM,data:ag7LKoMw,iv:gPyvQ3jt2wtOG7soFOoFsiYMGx6CoOBYQ2qF5cd5N70=,tag:jTKxI+275gbfpX8wcC2/9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cNw3/Y5J45JiTkoPvC28DY6NsWQ=,iv:FxOoEdn37BuVxQKWDiaflXgXWvhbzmxK9zvKBJv1MT8=,tag:wzSqJCZC13f8e3L/E+Tycw==,type:str]
    namespace: ENC[AES256_GCM,data:NG+p4SuLKHx2WlVDMQ==,iv:0dm9p7OcNjxDJTrL89sLpy3bd50/j6++Qhj+qncyGLY=,tag:xxg27oxeX57vxziyhjcmSw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:8b/z/0jxRlc=,iv:nyiBmCzet0LSslkQhYaRaK/Vu/xpqS1giq1qcfb7f2E=,tag:kPkPbJPvdAQLjQbjDagDKA==,type:str]
type: ENC[AES256_GCM,data:pFpfn7+0,iv:XAMlnDAmL6ocQtMrb4fe2dkdoVzXzoKAf7OsUGCrFNY=,tag:8XPsc9/FGeMbcFHsJwlV9w==,type:str]
stringData:
    PLACEHOLDER: ENC[AES256_GCM,data:dWOlQHPRDb0=,iv:4PbrZMj8YCCTWc67nhaVLQEgmIXEtorRIWTyVIQbCZA=,tag:3VY6CnC0cDHVGzfT/hT0JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r5cjptkyd4wn82y5flfte4lm7y67nk2wxqhm7ncg5v23ea6seq9sfyjl0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdnU4T1pPblEzdGxoNkxs
            alpjek9YTmZJRC9lMitzUDRveWpXM0RHOUc4CjBWUUd1SXR2cEs4M2IxaEhxSVdI
            RDVMK2pLRnU4dmQ0V1ArVGFUTDNYbDgKLS0tIHFERkp5c1RZcEtRYW1GUG80SFpt
            a1l1cXpGZHo0dGM1TTFrbGlDV1RFY3MKkrmVES29qCpjFi+khfhcXkjeTpNdyBQO
            XK2gPGo2cmydt/VM9f7V1GUTWsNAE8ELHHIVV/Y30W+L62l3KTULBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-11T21:27:36Z"
    mac: ENC[AES256_GCM,data:+mhzjJ2SIUTFxz04U+JrAAHvecAON7fsfyaj1ULBVSjEOZ3gVLQiAX8A5mW5Oscm4uf6QEFATcPPeylVGbRAwI6hdMiiIkb82A+q/VSTMWnFkzG0IVznl18jkMJ+6au4/KRvPNlKOOBcTMO6ht4LiCLq0gqbh0O2WJjGtOsMBF4=,iv:JBjI8PsjzAAptEUQFrE8fHrwMLv712fzaWlegJWzjAo=,tag:gRB4odVufh07GIl7tUEEOA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
